-- MySQL Script generated by MySQL Workbench
-- 09/11/14 14:34:47
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airlinedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airlinedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `airlinedb` ;

-- -----------------------------------------------------
-- Table `airlinedb`.`plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`plane` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pilot` INT NOT NULL DEFAULT 1,
  `navigator` INT NOT NULL DEFAULT 1,
  `radioman` INT NOT NULL DEFAULT 1,
  `steward` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `from` VARCHAR(45) NOT NULL,
  `to` VARCHAR(45) NOT NULL,
  `plane_id` INT NOT NULL,
  PRIMARY KEY (`id`, `plane_id`),
  INDEX `fk_flight_plane1_idx` (`plane_id` ASC),
  CONSTRAINT `fk_flight_plane1`
    FOREIGN KEY (`plane_id`)
    REFERENCES `airlinedb`.`plane` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(12) NOT NULL,
  `pass` VARCHAR(12) NOT NULL,
  `position_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `position_id`, `role_id`, `person_id`),
  INDEX `fk_employee_position1_idx` (`position_id` ASC),
  INDEX `fk_employee_role1_idx` (`role_id` ASC),
  INDEX `fk_employee_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `airlinedb`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `airlinedb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `airlinedb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`crew` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flight_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  INDEX `fk_crew_flight1_idx` (`flight_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_crew_flight1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `airlinedb`.`flight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crew_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `airlinedb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
airlinedbcrew