-- MySQL Script generated by MySQL Workbench
-- 09/14/14 11:48:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airlinedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airlinedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `airlinedb` ;

-- -----------------------------------------------------
-- Table `airlinedb`.`plane_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`plane_staff` (
  `plane` INT NOT NULL AUTO_INCREMENT,
  `pilot` INT NOT NULL DEFAULT 1,
  `navigator` INT NOT NULL DEFAULT 1,
  `radioman` INT NOT NULL DEFAULT 1,
  `steward` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`plane`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `from` VARCHAR(45) NOT NULL,
  `to` VARCHAR(45) NOT NULL,
  `plane_staff_plane` INT NOT NULL,
  PRIMARY KEY (`id`, `plane_staff_plane`),
  INDEX `fk_flight_plane_staff1_idx` (`plane_staff_plane` ASC),
  CONSTRAINT `fk_flight_plane_staff1`
    FOREIGN KEY (`plane_staff_plane`)
    REFERENCES `airlinedb`.`plane_staff` (`plane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `position_id`),
  INDEX `fk_employee_position1_idx` (`position_id` ASC),
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `airlinedb`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`crew` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flight_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  INDEX `fk_crew_flight1_idx` (`flight_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_crew_flight1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `airlinedb`.`flight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crew_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `airlinedb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airlinedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airlinedb`.`user` (
  `login` VARCHAR(12) NOT NULL,
  `pass` VARCHAR(12) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`login`, `role_id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `airlinedb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
